### ISSUE TITLE
Some installation issues

### ISSUE THREAD

**Issue by Joanne02** [comet-app/contributing#1]
Now, I plan to install a website like www.getcomet.net on my server.

But this tutorial just tells me some key installation steps. I cannot complete my plan through the tutorial.

I hope I can get some help, thanks!

**completed:**

1. I have purchased the server (centos 7) and domain name, then configured my domain to point to my server's public ip address.

2. Node.js 14.5.0 and npm 6.14.5 have been installed

3. Data PostgreSQL 12 has been installed, and configuration port: 5432; username: postgres; password: password; database: postgres.

4. git clone https://github.com/comet-app/web and https://github.com/comet-app/server

5. cd web --> npm install; cd server-->npm install

**undone:**

1. I don't know how to configure Environment variables
2. How to set up to visit my website through the domain instead of https://localhost:3000.

thank! thank!

**Comment by danbeneventano** [comment]
Your questions are specific to your environment and not related to Comet
